apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: end-to-end-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CuteDandelion/End-to-End-Data-Pipeline.git
    targetRevision: master
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
